name: Wallpaper report
description: File a wallpaper issue
labels: ["wallpaper"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report this wallpaper issue!
        Please provide us with the necessary information to help us understand and address the problem.
  - type: input
    id: wallpaper-location
    attributes:
      label: Wallpaper Location
      description: Where did you find this wallpaper? Please provide its name if possible.
      placeholder: "Example: Game/Night City-1"
    validations:
      required: true
  - type: dropdown
    id: report-reason
    attributes:
      label: Report Reason
      description: Why are you reporting this wallpaper?
      multiple: false
      options:
        - Other
        - Nudity or Violence
        - Copyright Violation
        - Harmful or Malicious
        - Misleading Information
    validations:
      required: true
  - type: textarea
    id: report-description
    attributes:
      label: Report Description
      description: |
        Please describe the issue in detail:
        - How should it appear instead?
        - What specifically is wrong with the wallpaper?
        - Any additional information that might help us understand the problem.
      placeholder: Describe the issue...
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: Please provide the version of the application you are using.
      placeholder: "24.7.25.0"
    validations:
      required: true
  - type: input
    id: theme-version
    attributes:
      label: Theme Version
      description: Please provide the theme version (enter "-" if unknown).
      placeholder: "1.0.0.0"
    validations:
      required: true
  - type: input
    id: theme-app-version
    attributes:
      label: Theme App Version
      description: Please provide the theme app version (enter "-" if unknown).
      placeholder: "24.7.23.0"
    validations:
      required: true